# Generated by Django 6.0 on 2025-12-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], null=True, verbose_name='day of week'),
        ),
    ]
